### ISSUE TITLE
Multi clients support

### ISSUE THREAD

**Issue by mainameiz** [toptal/chewy#338]
I want to implement multi-client support as it is in mongoid where you can specify different hosts for different collections.

E.g.

``` yaml
# chewy.yml

production:
  clients:
    default:
      hosts: "localhost:9200"
    search:
      hosts: "localhost:9201"
```

``` ruby
# app/chewy/search_index.rb

class SearchIndex < Chewy::Index
  client :search
end
```

Is it a good idea? Do you have any suggestions about this feature?
