### ISSUE TITLE
Dynamic index name for tests to be able run in parallel

### ISSUE THREAD

**Issue by ka8725** [toptal/chewy#342]
Assume the following case: there is an one instance of ES and we would like to use it in tests and we want to run the tests in parallel. When we have 2 or more working instances in tests simultaneously we have race conditions - so one of the tests instance deletes index and the others try to read documents from it and this leads to crashing our tests.

Currently we solved the issue in the following way (this is `rspec` config):

```ruby
RSpec.configure do |config|
  config.before(:suite) do
    Index1.index_name("#{Index1.index_name}-#{Time.zone.now.to_i}")
    Index2.index_name("#{Index2.index_name}-#{Time.zone.now.to_i}")
    # ...
  end

  config.around do |example|
    Chewy.massacre if example.metadata[:clear_elastic]
    example.run
  end
end
```

So the index names are uniq per tests instance, they can be deleted freely or created any time independently what is going on in other instances.

I tried to do the same trick using `.purge!` and `.create!` method in the `Chewy::Index` with prefixes but unfortunately couldn't manage to get a working solution because `.purge!` deletes all indexes as they are just **aliases**. So seems this is the only one working solution for now. Please, correct me if this is not true.

If this is the only one correct solution for now I propose to introduce an option in chewy's config. So it would something like this:

```ruby
Chewy.generate_dynamic_index_names = false # default value
Index1.index_name # => 'index1'
Chewy.generate_dynamic_index_names = true
Index1.index_name # => 'index1-1456532536'
```

What do you think, guys?

**Comment by pyromaniac** [comment]
This is our chewy.yml

```
test: &test
  host: 'localhost:9250'
  prefix: test<%= ENV['TEST_ENV_NUMBER'] %>
  wait_for_status: green
  index:
    number_of_shards: 1
    number_of_replicas: 0

cucumber:
  <<: *test
  prefix: cucumber<%= ENV['TEST_ENV_NUMBER'] %>
```
