### ISSUE TITLE
Reconnect to elastic nodes on node failure

### ISSUE THREAD

**Issue by sharkzp** [toptal/chewy#389]
Hello everyone,

Recently we experienced issue with one of the elasticsearch nodes. Here is a setup

```
{
  "cluster_name" : "search",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 3,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 16,
  "active_shards" : 32,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0
}
```

As you could see we have three physical servers. Here is a Chewy config for it:

```
production:
  hosts:
    - "A"
    - "B"
    - "C"
  strategy: :atomic
  randomize_hosts: true
  retry_on_failure: true
  reload_on_failure: true
  transport_options:
    request:
      open_timeout: 1
      timeout: 45
```

Once Host `C` failed we start getting 500 exception with a message
`HTTPClient::ConnectTimeoutError: execution expired`
Which we assume means that Elasticsearch Ruby unable to connect to failed node. 
Any reason why we don't have any fallback on this point? I thought in that case elasticsearch-ruby or chewy will try to use next node in a list. 

After that we also tried to add this code in config.ru to reconnect on fork which also doesn't seem to work.
Even after node restart and availability we still have same exception until we reload pessanger completely. Any help will be much appreciated.

```
if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    if forked
      Chewy.client.transport.reload_connections!
    else
    end
  end
end
```
